### ISSUE TITLE
Feature: enable throwing a `SpamDetectedException` when spam is detected

### ISSUE THREAD

**Issue by kbond** [omines/antispam-bundle#11]
I think there should be an option for a `SpamDetectedException` be thrown. This enables an app to catch this and add their own fake success system globally. For instance, catch this exception in an exception listener, then redirect to homepage with a "thank you" flash to imply the form was processed correctly.

My thinking (at least for profiles), is a config like this:

```yaml
antispam:
  profiles:
    default:
      throw: true
```

Or maybe a mode option as this option isn't compatible with passive mode:

```yaml
antispam:
  profiles:
    default:
      mode: exception # one of "exception", "passive", "error"
```
