### ISSUE TITLE
Feature: Rate Limiting

### ISSUE THREAD

**Issue by kbond** [omines/antispam-bundle#3]
First of all, nice bundle! The docs are beautiful!

I have my own home grown honeypot/short submit system that I'm going to switch to this bundle.

Recently, we have been getting hammered by spam that gets past these two protections so I've implemented a rate limiting system: "can only submit a valid form once per minute and 5 times per hour"

Thought it could be a nice feature for this bundle.

**Comment by curry684** [comment]
Thanks for the kind words   💯 

Rate limiting is most certainly one to be put on the list. I'm also considering wrapping up Recaptcha, [Akismet](https://github.com/omines/akismet) and maybe even the classic math questions in here!

**Comment by curry684** [comment]
By the way you should most definitely also look at the URL counting and banned scripts. On most of our sites we're getting hammered by Cyrillic spam. On our company website this bundle has already managed to reduce spam to literally zero like this:
```yaml
antispam:
    profiles:
        default:
            banned_scripts:
                scripts: [cyrillic]
                max_percentage: 40

            url_count:
                max: 3
                max_identical: 1

            honeypot: email_address

            timer:
                min: 3
                max: 14400
```
