### ISSUE TITLE
Feature: logging

### ISSUE THREAD

**Issue by kbond** [omines/antispam-bundle#5]
I think it would be nice to have a `LoggingSubscriber` that listens to the `ValidatorViolationEvent` and log errors. This could be enabled/disabled via the bundle config:

```yaml
antispam:
    logging:
        enabled: true
        level: notice
```

If interested, I can work on this.
