### ISSUE TITLE
Feature: more robust honeypot widget

### ISSUE THREAD

**Issue by kbond** [omines/antispam-bundle#8]
I've read in a few places that bots understand `display: none` and know not to fill this field. This is an interesting article that shows an alternative: https://blog.stefanolaru.com/how-to-make-the-honeypot-field-more-effective

I mean, if a bot can understand `display: none`, they can likely determine it isn't in the viewport but... maybe it's just something that can help filter out the less advanced bots? I also feel it's better in a separate css style sheet - maybe this could be an option (add a generic class to this widget)?

**Comment by kbond** [comment]
Maybe a nice solution could be attribute configuration:

```yaml
antispam:
    profiles:
        default:
            honeypot: 
                field: email_address
                attributes:
                    style: 'display: none;'
                    autocomplete: 'nope'
                    tabindex: '-1'
```

Perhaps the above could be the default but the docs could show different approaches?
