### ISSUE TITLE
Doc: enable antispam for specific functional tests

### ISSUE THREAD

**Issue by kbond** [omines/antispam-bundle#9]
As I suggested in the recipe PR, I think for most of your application's tests, you'd want antispam disabled.

```yaml
# config/packages/antispam.yaml

when@test:
    antispam:
        profiles:
            default:
                passive: true
```

In my app, I wanted to have just a single test that ensured the antispam system (short submit specifically) was working. This was my solution:

```yaml
# config/packages/antispam.yaml

when@test:
    antispam:
        profiles:
            default:
                passive: '%env(not:default::ENABLE_ANTISPAM)%' # Disable antispam for tests unless ENABLE_ANTISPAM=1
```

Then, at the beginning of the test you want antispam enabled, add the following:

```php
/**
 * @test
 */
public function antispam_short_submit(): void
{
    $_ENV['ENABLE_ANTISPAM'] = '1';

    // create client, submit form and ensure spam was detected
}
```

You also need to unset this environment variable in the test case's tearDown method to ensure subsequent tests do not have this environment variable set:

```php
protected function tearDown(): void
{
    unset($_ENV['ENABLE_ANTISPAM']);
}
```

Of course, I may have missed an easier way to achieve this.

Anyway, I don't think we should set this as the default in the recipe as it's a bit tricky to reason about. I was thinking maybe a little note in the docs somewhere?
